name: 'Install dependencies'
description: 'Prepare repository and all dependencies'

runs:
  using: composite
  steps:
    - name: Setup Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Setup pnpm version 8
      uses: pnpm/action-setup@v3
      with:
        version: 8

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install Dependencies
      shell: bash
      run: pnpm install
